"""initial schema

Revision ID: b3b0098f789a
Revises:
Create Date: 2026-01-22 01:05:14.440289

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3b0098f789a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "doctors",
        sa.Column("doctor_id", sa.String(length=36), nullable=False),
        sa.Column("doctor_code", sa.String(length=12), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("specialty", sa.String(length=50), nullable=True),
        sa.Column("contact_info", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("doctor_id"),
        sa.UniqueConstraint("doctor_code"),
    )
    op.create_table(
        "patients",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("patient_code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("gender", sa.String(length=10), nullable=False),
        sa.Column("contact_info", sa.String(length=200), nullable=False),
        sa.Column("medical_history", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("patient_id"),
        sa.UniqueConstraint("patient_code"),
    )
    op.create_table(
        "user_roles",
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("role_code", sa.String(length=20), nullable=False),
        sa.Column("role_name", sa.String(length=50), nullable=False),
        sa.Column("parent_role_id", sa.String(length=36), nullable=True),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_role_id"],
            ["user_roles.role_id"],
        ),
        sa.PrimaryKeyConstraint("role_id"),
        sa.UniqueConstraint("role_code"),
    )
    op.create_table(
        "appointments",
        sa.Column("appointment_id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("doctor_id", sa.String(length=36), nullable=False),
        sa.Column("appointment_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "CHECKED_IN",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                "NO_SHOW",
                name="appointment_status",
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.doctor_id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.patient_id"],
        ),
        sa.PrimaryKeyConstraint("appointment_id"),
    )
    op.create_table(
        "schedules",
        sa.Column("schedule_id", sa.String(length=36), nullable=False),
        sa.Column("doctor_id", sa.String(length=36), nullable=False),
        sa.Column(
            "day_of_week",
            sa.Enum(
                "MONDAY",
                "TUESDAY",
                "WEDNESDAY",
                "THURSDAY",
                "FRIDAY",
                "SATURDAY",
                "SUNDAY",
                name="day_of_week",
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.doctor_id"],
        ),
        sa.PrimaryKeyConstraint("schedule_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schedules")
    op.drop_table("appointments")
    op.drop_table("user_roles")
    op.drop_table("patients")
    op.drop_table("doctors")
    # ### end Alembic commands ###
